trigger:
  - main  # Adjust if your branch is different

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Install Node.js'

  - script: |
      npm installtrigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Install Node.js'

  - script: |
      npm install
    displayName: 'Install dependencies'

  - script: |
      npx playwright install
    displayName: 'Install Playwright Browsers'

  - script: |
      npm test
    displayName: 'Run playwright-single.js'

    workingDirectory: Playwright-main
    displayName: 'Install dependencies'

  - script: |
      npx playwright install
    workingDirectory: Playwright-main
    displayName: 'Install Playwright Browsers'

  - script: |
      npm test
    workingDirectory: Playwright-main
    displayName: 'Run playwright-single.js'
