trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Install Node.js'

  - script: |
      npm install
    displayName: 'Install dependencies'

  - script: |
      npx playwright install --with-deps
    displayName: 'Install Playwright Browsers with dependencies'

  - script: |
      npx playwright test --reporter=junit
    displayName: 'Run Playwright Tests with JUnit Reporter'

  - task: LambdatestResults@1
    inputs:
      username: 'kabirk' # Better to use pipeline variable $(LT_USERNAME)
      accessKey: 'LT_RhMHqS2TJ4lYNmnzOfTYRaNYNdbFdvoDAKSFTVknI2UQBth' # Better to use $(LT_ACCESS_KEY)
      frameworkName: 'playwright'
      testResultPath: 'test-results/results.xml' # MUST match where your JUnit XML is generated
    displayName: 'Upload LambdaTest Results'
